### PR TITLE
[DEV APPROVED] update ruby version to 2.2.0

### PR DESCRIPTION
**Pull request by pmcostello**
update ruby-version to 2.2.0 dependency for mime-types-data gem

### CODE REVIEW

**Comment by tomas-stefano** [comment]
👍

**Comment by rnalexander** [comment]
:+1: Can someone configure the travis CI for this build to stop trying to go against earlier ruby versions?

**Comment by tomas-stefano** [comment]
@rnalexander https://github.com/moneyadviceservice/mas-feedback/pull/6

**Comment by Tr4pSt3R** [comment]
👍

**Pull request closed without merging**
